Insert into N_RS_CADASTRALMUNICIPALITY (COUNTRYID,CADDISTID,SUSID,RECORDTYPE,ADMINMUNID,"LEVEL",LABEL,NAME,BEGINLIFESPANVERSION,ENDLIFESPANVERSION,SIGN,ACTIVE,AREAHAS,AREASHOULD,GEOMETRY) 
    values ('1','46',NRSCADASTRALMUNICIPALITY_SEQ.NEXTVAL,null,'270',null,'723070','LAZAREVAC',null,null,null,'1',null,null,null);


